export enum TaskActions {
	ADD_TASK,
	EDIT_TASK,
	CHOOSE_TASK,
	TOGGLE_TASK,
	SAVE_TASK,
	CANCEL_EDIT_TASK
}

export enum FilterActions {
	SET_ACTIVE_FILTER,
	SET_SEARCH_TEMPLATE
}

export enum EditActions {
	//TODO
}

export enum CategoryActions {
	ADD_CATEGORY,
	CHOOSE_CATEGORY,
	SHOW_TASK_LIST,
	EDIT_CATEGORY,
	TOGGLE_CATEGORY,
	DELETE_CATEGORY,
	NEST_CATEGORY,
	ADD_SUBCATEGORY,
	CHANGE_CATEGORY_TITLE
}