export enum TaskActions {
	ADD_TASK,
	EDIT_TASK,
	CHOOSE_TASK,
	TOGGLE_TASK,
	SAVE_TASK,
	CANCEL_TASK_EDIT
}

export enum CategoryActions {
	ADD_CATEGORY,
	CHOOSE_CATEGORY,
	SHOW_TASK_LIST,
	EDIT_CATEGORY,
	TOGGLE_CATEGORY,
	DELETE_CATEGORY,
	NEST_CATEGORY,
	ADD_SUBCATEGORY
}

export enum FilterActions {
	TOGGLE_ACTIVE_FILTER,
	SET_SEARCH_TEMPLATE
}